#### Dataset
oxford-iiit-pet

In [1]:
import pandas as pd
import cv2
import numpy as np
import os

In [2]:
Height = 128
Width= 128
input_shape = (128,128,3)
NumOfCategories = 3

# Load Data

In [3]:
path = "./oxford-iiit-pet/"
trainFile = path + "annotations/trainval.txt"
testFile = path + "annotations/test.txt"

In [4]:
# train
allImages = []
maskImages = []

In [5]:
df = pd.read_csv(trainFile, sep=" ", header=None) # load the train images and the original masks 

names = df[0].values # list of file names

In [6]:
# df

In [7]:
# load the images

for name in names :
    # Image
    imageFileName = path + "images/" + name + ".jpg"   # Image file path
    img = cv2.imread(imageFileName , cv2.IMREAD_COLOR) # Load the image in color using OpenCV
    img = cv2.resize(img, (Width,Height))              # Resize the image to the specified width and height
    img = img / 255.0                                  # Normalize the image pixel values to the range [0, 1]
    img = img.astype(np.float32)                       # Convert the image data type to np.float32
    allImages.append(img)                              # Append the image to the list of all images

    # mask
    maskFileName = path + "annotations/trimaps/" + name + ".png" # Mask file path
    mask = cv2.imread(maskFileName , cv2.IMREAD_GRAYSCALE)       # gray scale images
    mask = cv2.resize(mask , (Width, Height))                    # Resize the mask to the specified width and height
    maskImages.append(mask)                                      # Append the mask image to the list

In [8]:
# Convert the lists of images and masks to NumPy arrays
allImagesNP = np.array(allImages)
maskImagesNP = np.array(maskImages)

# Convert the mask images to integer data type
maskImagesNP = maskImagesNP.astype(int)

In [9]:
print(allImagesNP.shape)
print(allImagesNP.dtype)

print(maskImagesNP.shape)
print(maskImagesNP.dtype)

(3680, 128, 128, 3)
float32
(3680, 128, 128)
int32


In [10]:
maskImagesNP.shape

(3680, 128, 128)

In [11]:
# For see the image as a numpy array
# Resize the first mask image in maskImagesNP to a size of (16, 16) using nearest-neighbor interpolation
x = cv2.resize(maskImagesNP[0], (16,16), interpolation=cv2.INTER_NEAREST)
print(x)

# value == 1 -> main object
# value == 2 -> background
# value == 3 -> border of the object

[[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 3 2 2 2 3 1 2 2]
 [2 2 2 2 2 2 3 1 1 3 3 3 1 3 2 2]
 [2 2 2 2 2 2 3 1 1 1 1 1 1 3 2 2]
 [2 2 2 2 3 1 1 1 1 1 1 1 1 3 2 2]
 [2 2 2 3 1 1 1 1 1 1 1 1 1 3 2 2]
 [2 2 3 1 1 1 1 1 1 1 1 1 3 3 2 2]
 [2 2 3 1 1 1 1 1 1 1 1 3 2 2 2 2]
 [2 2 3 1 1 1 1 1 1 1 1 2 2 2 2 2]
 [2 2 3 1 1 1 1 1 1 1 1 3 2 2 2 2]
 [2 2 3 1 1 1 1 1 1 3 2 2 2 2 2 2]
 [2 2 2 3 3 3 1 1 3 2 2 2 2 2 2 2]
 [2 2 2 2 3 3 3 1 3 2 2 2 2 2 2 2]
 [2 2 2 2 3 1 1 3 2 2 2 2 2 2 2 2]]


In [12]:
# Test
allTestImages = []
maskTestImages = []

# Load test data
df = pd.read_csv(testFile, sep=" ", header=None)
names = df[0].values # get the list of files

In [13]:
for name in names :
    # Image
    imageFileName = path + "images/" + name + ".jpg"   # Image file path
    img = cv2.imread(imageFileName , cv2.IMREAD_COLOR) # Load the image in color using OpenCV
    img = cv2.resize(img, (Width,Height))              # Resize the image to the specified width and height
    img = img / 255.0                                  # Normalize the image pixel values to the range [0, 1]
    img = img.astype(np.float32)                       # Convert the image data type to np.float32
    allTestImages.append(img)                          # Append the image to the list of all images

    # mask
    maskFileName = path + "annotations/trimaps/" + name + ".png" # Mask file path
    mask = cv2.imread(maskFileName , cv2.IMREAD_GRAYSCALE)       # gray scale images
    mask = cv2.resize(mask , (Width, Height))                    # Resize the mask to the specified width and height
    maskTestImages.append(mask)                                  # Append the mask image to the list

In [14]:
allTestImagesNP = np.array(allTestImages)
maskTestImagesNP = np.array(maskTestImages)

maskTestImagesNP = maskTestImagesNP.astype(int)

In [15]:
print(allTestImagesNP.shape)
print(allTestImagesNP.dtype)

print(maskTestImagesNP.shape)
print(maskTestImagesNP.dtype)

(3669, 128, 128, 3)
float32
(3669, 128, 128)
int32


In [16]:
# Create the "numpy_array" folder if it doesn't already exist
if not os.path.exists("numpy_array"):
    os.makedirs("numpy_array")

In [17]:
# save numpy array
np.save("./numpy_array/allImagesNP.npy",      allImagesNP)
np.save("./numpy_array/maskImagesNP.npy",     maskImagesNP)
np.save("./numpy_array/allTestImagesNP.npy",  allTestImagesNP)
np.save("./numpy_array/maskTestImagesNP.npy", maskTestImagesNP)